// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRecentSearches(arg1) {
  return window['go']['main']['App']['GetRecentSearches'](arg1);
}

export function TrackShipment(arg1) {
  return window['go']['main']['App']['TrackShipment'](arg1);
}
